# Generated by Django 5.1.5 on 2025-01-16 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryMgtSys', '0002_user_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='gross_qty_mt',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='net_qty_mt',
        ),
        migrations.AddField(
            model_name='deal',
            name='gross_qty',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='deal',
            name='net_qty',
            field=models.FloatField(default=0.0),
        ),
    ]
