# Generated by Django 5.1.6 on 2025-03-04 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('CustomerID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Contact', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryStaff',
            fields=[
                ('StaffID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Contact', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('MenuID', models.AutoField(primary_key=True, serialize=False)),
                ('Item', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('RestaurantID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('OrderID', models.AutoField(primary_key=True, serialize=False)),
                ('OrderDate', models.DateTimeField(auto_now_add=True)),
                ('CustomerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.customer')),
                ('DeliveryStaffID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.deliverystaff')),
                ('Items', models.ManyToManyField(to='delivery.menu')),
                ('RestaurantID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.restaurant')),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='RestaurantID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.restaurant'),
        ),
    ]
