# Generated by Django 5.1.4 on 2025-01-11 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='music/')),
                ('cover_art', models.ImageField(blank=True, null=True, upload_to='covers/')),
            ],
        ),
    ]
