# Generated by Django 5.1.6 on 2025-03-26 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='book_name',
        ),
    ]
